acceptance/openstack/clientconfig/clientconfig_test.go
openstack/auth_yaml.go
openstack/clientconfig/doc.go
openstack/clientconfig/requests.go
openstack/clientconfig/results.go
openstack/clientconfig/testing/clouds.yaml
openstack/clientconfig/testing/fixtures.go
openstack/clientconfig/testing/requests_test.go
openstack/clientconfig/utils.go

This commit introduces the clientconfig package. clientconfig
is based on the Python os-client-config library and will offer
convenience functions for creating OpenStack clients.

clientconfig package

---

acceptance/gnocchi/metric/v1/archivepolicies_test.go
acceptance/gnocchi/metric/v1/pkg.go
gnocchi/metric/v1/archivepolicies/doc.go
gnocchi/metric/v1/archivepolicies/requests.go
gnocchi/metric/v1/archivepolicies/results.go
gnocchi/metric/v1/archivepolicies/testing/doc.go
gnocchi/metric/v1/archivepolicies/testing/fixtures.go
gnocchi/metric/v1/archivepolicies/testing/requests_test.go
gnocchi/metric/v1/archivepolicies/urls.go
gnocchi/metric/v1/common/common_tests.go
gnocchi/testhelper/client/fake.go

Add Gnocchi archive policy structure and list request.
Add unit tests and fake Gnocchi service client for tests.
`gnocchi archive-policy list`
Links to the line numbers/files in the Gnocchi source code that support the
https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/rest/api.py#L333
https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/indexer/sqlalchemy.py#L563
https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/archive_policy.py#L29

Implement Gnocchi archive policy list

---

acceptance/gnocchi/metric/v1/metrics_test.go
gnocchi/metric/v1/metrics/doc.go
gnocchi/metric/v1/metrics/requests.go
gnocchi/metric/v1/metrics/results.go
gnocchi/metric/v1/metrics/testing/doc.go
gnocchi/metric/v1/metrics/testing/fixtures.go
gnocchi/metric/v1/metrics/testing/requests_test.go
gnocchi/metric/v1/metrics/urls.go

Add Gnocchi metric structure and list request.
`gnocchi metric list`
https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/rest/api.py#L447
https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/indexer/sqlalchemy.py#L689

Implement Gnocchi metric list

---

acceptance/gnocchi/metric/v1/resources_test.go
gnocchi/metric/v1/resources/doc.go
gnocchi/metric/v1/resources/requests.go
gnocchi/metric/v1/resources/results.go
gnocchi/metric/v1/resources/testing/doc.go
gnocchi/metric/v1/resources/testing/fixtures.go
gnocchi/metric/v1/resources/testing/requests_test.go
gnocchi/metric/v1/resources/urls.go
gnocchi/results.go
internal/pkg.go
internal/testing/pkg.go
internal/testing/util_test.go
internal/util.go

Add Gnocchi resource structure and list request.
`gnocchi resource list`
https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/rest/api.py#L1126
https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/indexer/sqlalchemy.py#L988

Implement Gnocchi resource list

---

gnocchi/metric/v1/metrics/doc.go
gnocchi/metric/v1/metrics/requests.go
gnocchi/metric/v1/metrics/results.go
gnocchi/metric/v1/metrics/testing/fixtures.go
gnocchi/metric/v1/metrics/testing/requests_test.go
gnocchi/metric/v1/metrics/urls.go

Add Gnocchi metric get request and unit test.
`gnocchi metric show`
https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/rest/api.py#L1836
https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/indexer/__init__.py#L41

Implement Gnocchi metric get

---

acceptance/gnocchi/metric/v1/resources_test.go
gnocchi/metric/v1/resources/doc.go
gnocchi/metric/v1/resources/requests.go
gnocchi/metric/v1/resources/results.go
gnocchi/metric/v1/resources/testing/fixtures.go
gnocchi/metric/v1/resources/testing/requests_test.go
gnocchi/metric/v1/resources/urls.go

Add Gnocchi resource get request and unit test.
`gnocchi resource show`
https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/rest/api.py#L994
https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/indexer/sqlalchemy.py#L936

Implement Gnocchi resource get

---

acceptance/gnocchi/metric/v1/metrics.go
acceptance/gnocchi/metric/v1/metrics_test.go
gnocchi/metric/v1/metrics/doc.go
gnocchi/metric/v1/metrics/requests.go
gnocchi/metric/v1/metrics/results.go
gnocchi/metric/v1/metrics/testing/fixtures.go
gnocchi/metric/v1/metrics/testing/requests_test.go
gnocchi/metric/v1/metrics/urls.go

Add Gnocchi metric create request with tests and documentation.
`gnocchi metric create`
https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/rest/api.py#L618
https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/indexer/sqlalchemy.py#L670

Implement Gnocchi metric creation

---

acceptance/gnocchi/metric/v1/metrics.go
acceptance/gnocchi/metric/v1/metrics_test.go
gnocchi/metric/v1/metrics/doc.go
gnocchi/metric/v1/metrics/requests.go
gnocchi/metric/v1/metrics/results.go
gnocchi/metric/v1/metrics/testing/requests_test.go
gnocchi/metric/v1/metrics/urls.go

Add Gnocchi metric delete request with tests and documentation.
`gnocchi metric delete`
https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/rest/api.py#L533
https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/indexer/sqlalchemy.py#L1118

Implement Gnocchi metric delete

---

gnocchi/metric/v1/measures/doc.go
gnocchi/metric/v1/measures/requests.go
gnocchi/metric/v1/measures/results.go
gnocchi/metric/v1/measures/testing/doc.go
gnocchi/metric/v1/measures/testing/fixtures.go
gnocchi/metric/v1/measures/testing/requests_test.go
gnocchi/metric/v1/measures/urls.go
gnocchi/results.go

Add Gnocchi measures list request with tests and documentation.
`gnocchi measures show`
API:
- https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/rest/api.py#L465
Storage code depends on a driver that is used for saving measures:
- Ceph: https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/storage/ceph.py#L140
- Redis: https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/storage/redis.py#L103
- File: https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/storage/file.py#L142
- S3: https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/storage …

Implement Gnocchi measures list

---

acceptance/gnocchi/metric/v1/resources.go
acceptance/gnocchi/metric/v1/resources_test.go
gnocchi/metric/v1/metrics/testing/requests_test.go
gnocchi/metric/v1/resources/doc.go
gnocchi/metric/v1/resources/requests.go
gnocchi/metric/v1/resources/results.go
gnocchi/metric/v1/resources/testing/fixtures.go
gnocchi/metric/v1/resources/testing/requests_test.go
gnocchi/metric/v1/resources/urls.go

Add Gnocchi resource create request with tests and documentation.
`gnocchi resource create`
https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/rest/api.py#L1092
https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/indexer/sqlalchemy.py#L745

Implement Gnocchi resource creation

---

acceptance/gnocchi/metric/v1/measures.go
acceptance/gnocchi/metric/v1/measures_test.go
gnocchi/metric/v1/measures/doc.go
gnocchi/metric/v1/measures/requests.go
gnocchi/metric/v1/measures/results.go
gnocchi/metric/v1/measures/testing/requests_test.go
gnocchi/metric/v1/measures/urls.go

Add Gnocchi measures create request with tests and documentation.
That request implements pushing measures to a single metric, without batching.
Docs reference: [rest#push](https://gnocchi.xyz/rest.html#push)
`gnocchi measures add`
API:
- https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/rest/api.py#L454
Storage code depends on a driver that is used for saving measures:
- Ceph: https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/incoming/ceph.py#L193
- Redis: https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/incoming/redis.py#L107
- File: …

Implement Gnocchi measures create

---

acceptance/gnocchi/metric/v1/resources_test.go
gnocchi/metric/v1/resources/doc.go
gnocchi/metric/v1/resources/requests.go
gnocchi/metric/v1/resources/results.go
gnocchi/metric/v1/resources/testing/fixtures.go
gnocchi/metric/v1/resources/testing/requests_test.go
gnocchi/metric/v1/resources/urls.go

Add Gnocchi resource create request with tests and documentation.
`gnocchi resource update`
https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/rest/api.py#L1007
https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/indexer/sqlalchemy.py#L788

Implement Gnocchi resource update

---

acceptance/gnocchi/metric/v1/resources.go
acceptance/gnocchi/metric/v1/resources_test.go
gnocchi/metric/v1/resources/doc.go
gnocchi/metric/v1/resources/requests.go
gnocchi/metric/v1/resources/results.go
gnocchi/metric/v1/resources/testing/fixtures.go
gnocchi/metric/v1/resources/testing/requests_test.go
gnocchi/metric/v1/resources/urls.go

Add Gnocchi resource delete request with tests and documentation.
`gnocchi resource delete`
https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/rest/api.py#L1050
https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/indexer/sqlalchemy.py#L896

Implement Gnocchi resource delete

---

acceptance/gnocchi/metric/v1/measures.go
acceptance/gnocchi/metric/v1/measures_test.go
gnocchi/metric/v1/measures/doc.go
gnocchi/metric/v1/measures/requests.go
gnocchi/metric/v1/measures/results.go
gnocchi/metric/v1/measures/testing/requests_test.go
gnocchi/metric/v1/measures/urls.go

Add ability to create measures of a different metrics via metrics IDs references.
Add unit and acceptance tests and a documentation example.
That request implements pushing measures to different metrics via batch request to metric IDs.
Those changes won't provide the ability that allow user to batch measures via resource IDs and metric names.
Docs reference: [rest.html#batch](https://gnocchi.xyz/rest.html#batch)
API:
- https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/rest/api.py#L1614
Storage code depends on a driver that is used for saving measures:
- Ceph: https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi …

Implement Gnocchi measures batch create via metrics IDs

---

acceptance/gnocchi/metric/v1/measures.go
acceptance/gnocchi/metric/v1/measures_test.go
acceptance/gnocchi/metric/v1/pkg.go
acceptance/gnocchi/metric/v1/resources.go
gnocchi/metric/v1/measures/doc.go
gnocchi/metric/v1/measures/requests.go
gnocchi/metric/v1/measures/results.go
gnocchi/metric/v1/measures/testing/fixtures.go
gnocchi/metric/v1/measures/testing/requests_test.go
gnocchi/metric/v1/measures/urls.go

Add ability to create measures of a different metrics via resource IDs and metrics names references.
Add unit and acceptance tests and a documentation example.
That request implements pushing measures to different metrics via batch request to resource IDs and metric names.
Docs reference: [rest.html#batch (second example)](https://gnocchi.xyz/stable_4.2/rest.html#batch)
API:
- https://github.com/gnocchixyz/gnocchi/blob/stable/4.2/gnocchi/rest/api.py#L1567
Storage code depends on a driver that is used for saving measures:
- Ceph: https://github.com/gnocchixyz/gnocchi/blob/stable/4.2/gnocchi/incoming/ceph.py#L81
- Redis: …

Implement Gnocchi measures batch create via resource IDs and metric names

---

gnocchi/metric/v1/measures/requests.go

Gnocchi measures value can contain 0. It's completely normal and
expected situation.
For #28

Do not set required tag on the MeasureOpts.Value

---

openstack/clientconfig/requests.go
openstack/clientconfig/results.go
openstack/clientconfig/testing/clouds.yaml
openstack/clientconfig/testing/fixtures.go
openstack/clientconfig/testing/requests_test.go
openstack/clientconfig/utils.go

This commit is a large refactor of the clientconfig package.
It attempts to become a single point of entry for all OpenStack
authentication, supporting authentication from clouds.yaml,
explicit authentication parameters, and environment variables.
Supersedes #26 
Requires https://github.com/gophercloud/gophercloud/pull/896
For https://github.com/gophercloud/gophercloud/issues/252

clientconfig refactor

---

.gitignore
openstack/clientconfig/requests.go
openstack/clientconfig/results.go
openstack/clientconfig/testing/clouds.yaml
openstack/clientconfig/testing/fixtures.go
openstack/clientconfig/testing/requests_test.go

For #45
@jtopjian : Please review when you got time. I was a bit unsure here what shall be done here. For example in Terraform Cloud struct is fetched [here](https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/config.go#L76) then it is easy to just fetch the values directly. Or shall some function be introduced?

clientconfig: Add support for SSL setting to disable verification

---

acceptance/gnocchi/metric/v1/archivepolicies.go
acceptance/gnocchi/metric/v1/archivepolicies_test.go
gnocchi/metric/v1/archivepolicies/doc.go
gnocchi/metric/v1/archivepolicies/requests.go
gnocchi/metric/v1/archivepolicies/results.go
gnocchi/metric/v1/archivepolicies/testing/fixtures.go
gnocchi/metric/v1/archivepolicies/testing/requests_test.go
gnocchi/metric/v1/archivepolicies/urls.go

Add support for creating Gnocchi archive policies.
Add unit test and example in documentation.
API reference:
https://gnocchi.xyz/stable_4.2/rest.html#id2
https://github.com/gnocchixyz/gnocchi/blob/stable/4.2/gnocchi/rest/api.py#L318
https://github.com/gnocchixyz/gnocchi/blob/stable/4.2/gnocchi/indexer/sqlalchemy.py#L606
For #42

Gnocchi: implement archive policy Create method

---

openstack/clientconfig/requests.go

Noticed a small bug which was introduced in PR #51 which generate error if clouds-public.yaml does not exists.

Fixes incorrect error when clouds-public.yaml is not found

---

acceptance/gnocchi/metric/v1/archivepolicies.go
acceptance/gnocchi/metric/v1/archivepolicies_test.go
gnocchi/metric/v1/archivepolicies/doc.go
gnocchi/metric/v1/archivepolicies/requests.go
gnocchi/metric/v1/archivepolicies/results.go
gnocchi/metric/v1/archivepolicies/testing/fixtures.go
gnocchi/metric/v1/archivepolicies/testing/requests_test.go
gnocchi/metric/v1/archivepolicies/urls.go

Add the Delete method to the archivepolicies package with tests and documentation example.
For #42
API reference:
https://gnocchi.xyz/rest.html#id5
https://github.com/gnocchixyz/gnocchi/blob/stable/4.2/gnocchi/rest/api.py#L299
https://github.com/gnocchixyz/gnocchi/blob/stable/4.2/gnocchi/indexer/sqlalchemy.py#L592

Gnocchi: implement archive policy Delete method

---

acceptance/gnocchi/metric/v1/archivepolicies_test.go
gnocchi/metric/v1/archivepolicies/doc.go
gnocchi/metric/v1/archivepolicies/requests.go
gnocchi/metric/v1/archivepolicies/results.go
gnocchi/metric/v1/archivepolicies/testing/fixtures.go
gnocchi/metric/v1/archivepolicies/testing/requests_test.go
gnocchi/metric/v1/archivepolicies/urls.go

Add support for updating Gnocchi archive policies.
Add unit test and example in documentation.
For #42 
API reference:
https://gnocchi.xyz/stable_4.2/rest.html#update
https://github.com/gnocchixyz/gnocchi/blob/stable/4.2/gnocchi/rest/api.py#L275
https://github.com/gnocchixyz/gnocchi/blob/stable/4.2/gnocchi/indexer/sqlalchemy.py#L572

Gnocchi: implement archive policy Update method

---

acceptance/gnocchi/metric/v1/resourcetypes_test.go
gnocchi/metric/v1/resourcetypes/doc.go
gnocchi/metric/v1/resourcetypes/requests.go
gnocchi/metric/v1/resourcetypes/results.go
gnocchi/metric/v1/resourcetypes/testing/doc.go
gnocchi/metric/v1/resourcetypes/testing/fixtures.go
gnocchi/metric/v1/resourcetypes/testing/requests_test.go
gnocchi/metric/v1/resourcetypes/urls.go

Add new resourcetypes package with List method.
Add tests and a documentation example.
https://github.com/gnocchixyz/gnocchi/blob/stable/4.2/gnocchi/rest/api.py#L953
https://github.com/gnocchixyz/gnocchi/blob/stable/4.2/gnocchi/indexer/sqlalchemy.py#L485
For #54

Gnocchi: implement resource types List method

---

acceptance/gnocchi/metric/v1/resourcetypes.go
acceptance/gnocchi/metric/v1/resourcetypes_test.go
gnocchi/metric/v1/resourcetypes/doc.go
gnocchi/metric/v1/resourcetypes/requests.go
gnocchi/metric/v1/resourcetypes/results.go
gnocchi/metric/v1/resourcetypes/testing/fixtures.go
gnocchi/metric/v1/resourcetypes/testing/requests_test.go
gnocchi/metric/v1/resourcetypes/urls.go

Implement Create method in the resourcetypes package.
Add unit and acceptance tests with documentation.
https://github.com/gnocchixyz/gnocchi/blob/stable/4.2/gnocchi/rest/api.py#L933
https://github.com/gnocchixyz/gnocchi/blob/stable/4.2/gnocchi/indexer/sqlalchemy.py#L354
For #54

Gnocchi: add Create method for Resource types

---

gnocchi/metric/v1/resourcetypes/doc.go
gnocchi/metric/v1/resourcetypes/requests.go
gnocchi/metric/v1/resourcetypes/testing/fixtures.go
gnocchi/metric/v1/resourcetypes/testing/requests_test.go
gnocchi/metric/v1/resourcetypes/urls.go

Provide a method go get a single resource type. Add unit test and documentation.
https://github.com/gnocchixyz/gnocchi/blob/stable/4.2/gnocchi/rest/api.py#L849
https://github.com/gnocchixyz/gnocchi/blob/stable/4.2/gnocchi/indexer/sqlalchemy.py#L452
For #54

Gnocchi: add Resourcetypes Get method

---

openstack/clientconfig/requests.go
openstack/clientconfig/results.go
openstack/clientconfig/testing/clouds.yaml
openstack/clientconfig/testing/fixtures.go
openstack/clientconfig/testing/requests_test.go
openstack/clientconfig/testing/secure.yaml
openstack/clientconfig/utils.go

For #41 
This PR introduces secure.yaml for clientconfig and also fixes the behaviour of clientconfig when reading public-clouds.yaml as observed by @haxorof in #41

Support for secure.yaml and public-clouds.yaml

---

acceptance/gnocchi/metric/v1/resourcetypes.go
acceptance/gnocchi/metric/v1/resourcetypes_test.go
gnocchi/metric/v1/resourcetypes/doc.go
gnocchi/metric/v1/resourcetypes/requests.go
gnocchi/metric/v1/resourcetypes/results.go
gnocchi/metric/v1/resourcetypes/testing/fixtures.go
gnocchi/metric/v1/resourcetypes/testing/requests_test.go
gnocchi/metric/v1/resourcetypes/urls.go

Implement Delete method in the resourcetypes package.
Add unit and acceptance tests with documentation.
https://github.com/gnocchixyz/gnocchi/blob/stable/4.2/gnocchi/rest/api.py#L913
https://github.com/gnocchixyz/gnocchi/blob/stable/4.2/gnocchi/indexer/sqlalchemy.py#L540
For #54

Gnocchi: add Delete method for Resource types

---

acceptance/gnocchi/metric/v1/resourcetypes_test.go
gnocchi/metric/v1/resourcetypes/doc.go
gnocchi/metric/v1/resourcetypes/requests.go
gnocchi/metric/v1/resourcetypes/results.go
gnocchi/metric/v1/resourcetypes/testing/fixtures.go
gnocchi/metric/v1/resourcetypes/testing/requests_test.go
gnocchi/metric/v1/resourcetypes/urls.go

Implement Update method in the resourcetypes package.
Add unit and acceptance tests with documentation.
https://github.com/gnocchixyz/gnocchi/blob/stable/4.2/gnocchi/rest/api.py#L858
https://github.com/gnocchixyz/gnocchi/blob/stable/4.2/gnocchi/indexer/sqlalchemy.py#L385
For #54

Gnocchi: add Update method for Resource types

---

openstack/clientconfig/requests.go

For #69 
This commit will make clientconfig only use an environment variable if
an authentication setting was not previously set. This is to fix issues
where an application consuming clientconfig has already determined that
environment variables are not required.
This behavior matches Python-based applications since specifying an
authentication setting on the command-line will take priority of an
environment variable.
/cc @ozerovandrei This will fix the issue seen in https://github.com/terraform-providers/terraform-provider-openstack/issues/434

clientconfig: Deprioritize Environment Variables

---

openstack/clientconfig/utils.go

There's a way to workaround this issue by setting OS_CLIENT_CONFIG_FILE
to the right path, it's still not ok to fail when a USER is not defined
in the system. This can happen in various scenarios, including running
within a container.
OS_CLIENT_CONFIG_FILE should be a feature and not a workaround for this
problem. If USER is not defined or the `~/.config/openstack` dir
doesn't exist, we should just move on.

Don't fail if USER is not defined

---

acceptance/gnocchi/metric/v1/resources.go
openstack/clientconfig/requests.go
openstack/clientconfig/results.go
openstack/clientconfig/testing/clouds.yaml
openstack/clientconfig/testing/fixtures.go
openstack/clientconfig/testing/requests_test.go

Auth: add application credential support

---

acceptance/gnocchi/metric/v1/resources.go
openstack/clientconfig/requests.go
openstack/clientconfig/results.go

Some yaml libraries use json tags to drive serialization for both, json
and yaml. This patch adds json tags to the clientconfig's structs to
support those libraries.
The lack of these tags has caused some integration issues with other
softare using packages like `ghodss/yaml`. An example of this can be
found in the PR linked below:
https://github.com/openshift/installer/pull/854

Add json tags to clientconfig's structs

---

.travis.yml
go.mod
go.sum

This is in preparation to switching [Terraform OpenStack provider](https://github.com/terraform-providers/terraform-provider-openstack) to go modules (see https://github.com/terraform-providers/terraform-provider-openstack/issues/656).
Enabling go modules throughout the dependency tree of the provider will make the switch and future upgrades easier.
This PR is a result of the following commands (in a clean Go `1.11.5` environment):
```sh
go mod init
go get ./...
go mod tidy
```

Enable go modules

---

go.mod
go.sum
terraform/auth/config.go
terraform/auth/doc.go
terraform/auth/types.go
terraform/auth/util.go

This commit adds initial support for Terraform authentication.
The primary reason for this feature is to decouple the Terraform
Swift Remote State backend support from the Terraform OpenStack
Provider, thus reducing Terraform core's dependency of the OpenStack
Provider.
However, this package can also be used in any other situation where
a user wants to make an OpenStack-based Terraform provider/tool.
For https://github.com/terraform-providers/terraform-provider-openstack/issues/686

Terraform Authentication

---

gnocchi/metric/v1/status/results.go
gnocchi/metric/v1/status/testing/fixtures.go
gnocchi/metric/v1/status/testing/requests_test.go

Rename MetricD to Metricd in status package.
Update tests and fixtures.
Documentation reference:
https://gnocchi.xyz/operating.html#metricd
For #85

Gnocchi: rename MetricD to Metricd

---

openstack/clientconfig/doc.go

Recently tried following this, Name is not valid but Cloud is.

Documentation fix-up

---

openstack/clientconfig/results.go
openstack/clientconfig/testing/results_test.go

Currently when we try to marshal Clouds, it produces a lot of fields with empty strings, which is not correct.
This patch adds "omitempty" tag to all Cloud fields to allow correct marshalling of the structure.

Add "omitempty" tag to marshal clouds right

---

terraform/auth/config.go

Resolves #103 
add Terraform OrchestrationV1Client support
This is required by  https://github.com/terraform-providers/terraform-provider-openstack/pull/944

Add Terraform OpenStack OrchestrationV1Client

---

client/client.go

Allow JSON patch logging in debug.
For example these requests: https://docs.openstack.org/api-ref/image/v2/?expanded=update-image-detail#update-image

Log json-patch content type

---

client/client.go

Followup for #109. I had to put a condition into a `logRequest` instead of `logResponse`.

Log json patch request instead of response

---

client/client.go

Initially in https://github.com/gophercloud/gophercloud/pull/1900 I used a wrong place to put EC2 auth parameters. They worked, but it didn't allow to use proper GET requests.

Mask Authorization header in ec2 auth body

---

gnocchi/metric/v1/metrics/requests.go
gnocchi/metric/v1/metrics/results.go
gnocchi/metric/v1/resources/requests.go
gnocchi/metric/v1/resources/results.go

In the current implementation, pager type of gnocchi metrics and resources list
is SinglePageBase, which is wrong. In Gnocchi, query results in one page
are limited to max_limit value set in the configuration file (default 1000).
With the current implementation, AllPages() method can only show the first
page of query result (the first 1000 metrics, for example).
The pager type should be MarkerPageBase and LastMarker() method needs to
be implemented.

Fixed gnocchi metrics and resources list pager

---

terraform/auth/config.go
terraform/auth/util.go
terraform/hashcode/hashcode.go
terraform/hashcode/hashcode_test.go
terraform/mutexkv/mutexkv.go
terraform/mutexkv/mutexkv_test.go

After [some discussion here](https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1080) with @ozerovandrei and @kayrus there is an intention to add globally available mutexkv and hashcode packages.

Add mutexkv and hashcode packages

---

terraform/auth/config.go

@jtopjian this PR allows external openstack based provider to use config methods + removed duplicate code for simple openstack service client.

terraform: export more methods, deduplicate client funcs

---

openstack/compute/v2/availabilityzones/utils.go

Add a new function, named ListAvailableAvailabilityZones, that return
a slice of AZs that are actually available.
Note: it uses availabilityzones.List() which doesn't require admin
privileges (comparing to availabilityzones.ListDetail() which does).

compute: add helper to return available AZs

---

internal/util.go
openstack/clientconfig/requests.go
terraform/auth/config.go
terraform/auth/util.go

Now, when we create a service client with gophercloud/utils, TLS options[1] are ignored, which leads to the fact that we can't work with self-signed certificates out of the box. Also it creates inconsistencies with python-openstackclient, where these options matter.
To remove the discrepancy this commit implements full TLS support.
The work is based on the Terraform client[2], and now that code is shared between the clients.
[1] https://github.com/gophercloud/utils/blob/88c6e9e533261350ec733e2e2147a1d3f8eb62de/openstack/clientconfig/results.go#L39-L49
[2] https://github.com/gophercloud/utils/blob/88c6e9e533261350ec733e2e2147a1d3f8eb62de/terraform/auth/config.go#L144-L179

Consider TLS options when we create a service client

---

internal/util.go

This commit contains two improvements to the existing TLS module:
1. Now the library ignores the fact the CA certificate can be broken (if it can't parse it for some reason, it just leaves an empty string
without a notice). From now we raise an error in this case.
2. It tries to prevent some obvious formatting errors in the certificate like leading and trailing spaces, additional new lines etc.

TLS improvements

---

openstack/compute/v2/images/utils.go

Use the Image Service instead of the deprecated image endpoint of the
Compute Service.

imageutils: Use the Image service

---

terraform/auth/config.go
terraform/mutexkv/mutexkv_test.go

We don't want to have a copy of the `sync.Locker` in the
`Config` since lock value shold not be copied.
Usually `Config` used as a singleton in different Terraform provider
resources and all of them should use a single `sync.Locker` instead of
different copies.
This commit changes `MutexKV` field of the `Config` to be a reference
instead of a copy and updates `MutexKV` tests to check that `MutexKV` is
used in a proper way.
Currently you can run `govet` linter and find the issue in the following files of the Terraform OpenStack provider:
https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/openstack/provider.go#L513
https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/openstack/resource_openstack_networking_router_route_v2. …

Terraform: use reference to MutexKV in Config

---

openstack/clientconfig/utils.go

While not clearly documented, the native openstacksdk package supports both
extensions. This brings parity with the official Python SDK.

clouds: support clouds.yml in addition to clouds.yaml

---

openstack/clientconfig/requests.go
openstack/clientconfig/results.go
openstack/clientconfig/testing/clouds.yaml
openstack/clientconfig/testing/fixtures.go
openstack/clientconfig/testing/requests_test.go
openstack/clientconfig/utils.go
terraform/auth/config.go

Failures due to "json: unsupported type: map[interface {}]interface {}" are
avoided by using jsoniter package. In addition, "complex" clouds.yaml are now
supported with per-region overrides (such as auth_url).
Fixes #68

fixes merging of clouds.yaml & secure.yaml

---

openstack/clientconfig/requests.go
openstack/clientconfig/utils.go

In addition wraps underline Errorf's errors.
Requires Go 1.13+
Fix #145.

clientconfig: fix file load error checks

---

openstack/clientconfig/requests.go

f41c176 introduced a custom HTTP client to make use of the self-signed
certificate specified in the clouds.yaml file. This change however
removed all the settings that came with the DefaultTransport, including
handling of proxy environment variables and default timeouts.
This commit ensures the custom HTTP client inherits its settings from
the default transport.
Requires golang 1.13.
Fixes #148

Use default transport settings for our custom TLS HTTP client

---

openstack/blockstorage/extensions/backups/utils.go
openstack/blockstorage/v1/snapshots/utils.go
openstack/blockstorage/v1/volumes/utils.go
openstack/blockstorage/v2/snapshots/utils.go
openstack/blockstorage/v2/volumes/utils.go
openstack/blockstorage/v3/snapshots/utils.go
openstack/blockstorage/v3/volumes/utils.go
openstack/compute/v2/flavors/utils.go
openstack/compute/v2/servers/utils.go
openstack/imageservice/v2/images/utils.go
openstack/networking/v2/networks/utils.go
openstack/networking/v2/ports/utils.go
openstack/networking/v2/subnets/utils.go
openstack/sharedfilesystems/v2/shares/utils.go
openstack/sharedfilesystems/v2/sharetypes/utils.go
openstack/sharedfilesystems/v2/snapshots/utils.go

This patch adds a function in the utils packages that returns all the
IDs of the items with the given name.
This patch leaves the behaviour of the existing `IDFromName` functions
untouched, while it reduces code duplication.

all: IDsFromName to return multiple results

---

openstack/clientconfig/requests.go
openstack/clientconfig/results.go
terraform/auth/config.go

AllowReauth cannot be set using `clientconfig`
This PR adds possibility to set this feature from AuthInfo in utils/clientconfig.
Signed-off-by: Ondrej Vasko <ondrej.vaskoo@gmail.com>

Add possibility to set AllowReauth in clientOpts

---

openstack/clientconfig/requests.go
openstack/clientconfig/testing/requests_test.go

The current behavior of the `GetCloudFromYAML` and `AuthOptions` utilities is confusing and the source of much pulled hair. As discussed in the linked bug, the equivalent Python libraries, openstacksdk and (legacy) os_client_config, both default to reading `OS_CLOUD` only if explicit cloud config has not been provided. However, we're actually overriding what the user provided if `OS_CLOUD` is set. This is clearly incorrect. Correct things to prefer user-provide cloud configuration, falling back to the environment variable only if this is not provided.
While we're here, correctly handle a nil `opts` arguments in the `GetCloudFromYAML` function. Previously this was done ad-hoc and was incomplete.
Closes: #164

clientconfig: Ignore OS_CLOUD if explicit cloud config provided

---

openstack/clientconfig/requests.go

The blockstorage v2 API [1] was deprecated in Pike and removed in Xena.
We should make v3 the default API version when none is explicitly
specified.
[1] https://docs.openstack.org/api-ref/block-storage/v2/

Default to blockstorage v3 API

---

openstack/clientconfig/testing/requests_test.go

Commit b2ceaa8efa963941aa70d34d113d27740a4545e9 broke some the unit
tests by deferring the cleanup of environment variables to when the
function exits. Wrap each test in it's own test function so that cleanup
happens when needed.

Fix client config unit tests

---

LICENSE

Reverting an unnecessary change that impaired Github's license parser.
This reverts commit 69fd486f595460d68a51478518e7fd9eebf6cf9d.

Revert "Credit the Gophercloud authors"

---

openstack/blockstorage/v3/availabilityzones/utils.go

Add a new function, `ListAvailableAvailabilityZones`, that will return a slice
of volume AZs that are available. This is the block storage equivalent of #130.

blockstorage: add helper to return available AZs

---

terraform/auth/config.go

In order to enable system scoped authorization in terraform-openstack-provider need the field authOpts in Config struct to be public.

terraform: make field AuthOpts public

---

terraform/auth/config.go

Related PR https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1517
Hope this is last PR to add system scoped authorization support to terraform-provider-openstack.
Builded and tested this time, provider "works on my PC" ;)
Debug logs from 
```
2023-03-24T01:03:43.329+0600 [INFO]  provider.terraform-provider-openstack_v1.51.0: 2023/03/24 01:03:43 [DEBUG] OpenStack Request Body: {
"auth": {
"identity": {
"methods": [
"password"
],
"password": {
"user": {
"domain": {
"name": "Default"
},
"name": "askar.sabyrov",
"password": "***"
}
}
},
"scope": {
"system": {
"all": true
}
}
}
}
```

[terraform] define SystemScope in AuthInfo

---

openstack/clientconfig/requests.go

There were a few missing services in `NewServiceClient()`.
This commit adds support for the `baremetal`, `baremetal-introspection`, `messaging`, and `workflowv2` services.

Add remaining services that gophercloud supports

---

terraform/auth/config.go

This fixes a dropped `err` variable in `terraform/auth`.

terraform/auth: fix dropped error

---

go.mod
go.sum
openstack/clientconfig/requests.go
openstack/clientconfig/testing/requests_test.go
openstack/clientconfig/testing/results_test.go

The changes in the test are required because since commit https://github.com/go-yaml/yaml/commit/ae27a744346343ea814bd6f3bdd41d8669b172d0 that was released in 3.0.0 causes extra whitespaces in the output.

Update dependency to gopkg.in/yaml.v3

---

go.mod
go.sum
openstack/clientconfig/requests.go

Replace import of hashicorp/go-uuid as its license MPL 2.0 is not incompatible with the license of the project Apache 2.0. Instead use gofrs/uuid which is compatible. It uses an MIT license.

Replace hashicorp/go-uuid import with gofrs/uuid

---

openstack/clientconfig/requests.go
openstack/clientconfig/utils.go

This picks up two dropped `err` variables in `openstack/clientconfig`.

openstack/clientconfig: fix dropped errors

---

terraform/auth/config.go

[terraform]: allow to override service type

---

gnocchi/metric/v1/archivepolicies/requests.go
gnocchi/metric/v1/measures/requests.go
gnocchi/metric/v1/measures/testing/requests_test.go
gnocchi/metric/v1/metrics/requests.go
gnocchi/metric/v1/resources/requests.go
gnocchi/metric/v1/resourcetypes/requests.go
gnocchi/metric/v1/status/requests.go

@mikaelgron can you check this fix?
Resolves #198 
maybe this is a better fix than https://github.com/gophercloud/gophercloud/pull/3188
Relates to https://github.com/gophercloud/gophercloud/issues/3184
Relates to https://github.com/gophercloud/gophercloud/pull/1942
Relates to https://github.com/gophercloud/gophercloud/pull/1952

Fix gnocchi EOF results

---

terraform/auth/config.go

`err` becomes `nil` in the `if err, ok := ...; { } else if err != nil {}` construction
detected in https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1899

terraform: fix incorrect error handling
