gophercloud/utils

- .travis.yml
- script/format
> initial travis support

- openstack/clientconfig/testing/clouds.yaml
- openstack/clientconfig/testing/fixtures.go
> clientconfig: updating tests

- openstack/clientconfig/requests.go
- openstack/clientconfig/testing/fixtures.go
> Allow Identity API version of 2

- openstack/clientconfig/requests.go
> clientconfig: add RegionName to ClientOpts

- openstack/clientconfig/requests.go
- openstack/clientconfig/results.go
- openstack/clientconfig/testing/clouds-public.yaml
- openstack/clientconfig/testing/clouds.yaml
- openstack/clientconfig/testing/fixtures.go
- openstack/clientconfig/testing/requests_test.go
- openstack/clientconfig/utils.go
Here is an updated version of what I did initially.
@jtopjian Please review and see if I shall change or add something.
As discussed this replaces PR #40
> clientconfig: Support for clouds-public.yaml

- openstack/clientconfig/requests.go
> fix error check in LoadSecureCloudsYAML

- acceptance/gnocchi/metric/v1/resources.go
Closes https://github.com/gophercloud/utils/issues/79
Thanks for your prompt response in the linked issue @jtopjian
> Replace satori/go.uuid w/ hashicorp/go-uuid

- gnocchi/metric/v1/status/doc.go
- gnocchi/metric/v1/status/requests.go
- gnocchi/metric/v1/status/results.go
- gnocchi/metric/v1/status/testing/doc.go
- gnocchi/metric/v1/status/testing/fixtures.go
- gnocchi/metric/v1/status/testing/requests_test.go
- gnocchi/metric/v1/status/urls.go
Add new status package with Get method.
Add tests and documentation example.
Code reference:
https://github.com/gnocchixyz/gnocchi/blob/stable/4.2/gnocchi/rest/api.py#L1959
For #85
> Gnocchi: implement status Get method

- acceptance/clients/clients.go
- env/env.go
- env/env_windows.go
- openstack/clientconfig/requests.go
- openstack/clientconfig/utils.go
Resolves https://github.com/gophercloud/gophercloud/issues/1572
> Proper special symbols encoding in windows

- openstack/clientconfig/requests.go
- openstack/clientconfig/testing/requests_test.go
- openstack/clientconfig/utils.go
> Allow Custom YAML Loading

- terraform/auth/config.go
- terraform/auth/util.go
This is an attempt to move forward the https://github.com/terraform-providers/terraform-provider-openstack/pull/688
> Sync Terraform auth func

- client/doc.go
@jtopjian the doc example was wrong, because of the changed format.
> Fix custom logger doc example

- openstack/clientconfig/requests.go
> Add client support for container-infra

- acceptance/openstack/objectstorage/v1/objects_test.go
- openstack/objectstorage/v1/objects/upload.go
This commit provides better file handling support when files and
file descriptors/pointers are being passed around. The files are
now wrapped or converted into a different type that protects
them from being closed at the Transport layer.
For https://github.com/gophercloud/gophercloud/issues/1856
> Object Storage v1: Better file handling support

- openstack/blockstorage/extensions/backups/utils.go
Resolves https://github.com/gophercloud/gophercloud/issues/1895
Followup for the #111
> Adding IDFromName function for blockstorage backups

- client/client.go
Prerequisite for https://github.com/gophercloud/gophercloud/issues/1898
> Mask EC2 access ID and body hash

- openstack/clientconfig/requests.go
> Fixing potential nil reference in GetCloudFromYAML

- openstack/helpers/projectpurge.go
During the cleanup of a project I ran in several challenges:
```bash
Expected HTTP response code [] when accessing [DELETE https://mycloud/v2.0/floatingips/0083695c-d17b-4ee7-8610-330d25bde798], but got 409 instead
{"NeutronError": {"type": "FipInUseByPortForwarding", "message": "Floating IP 0083695c-d17b-4ee7-8610-330d25bde798 in use by Port Forwarding resources.", "detail": ""}}
Error deleting floating IP: 0083695c-d17b-4ee7-8610-330d25bde798 from project: 7d44d6117b29422382837433bd266141
```
and
```bash
{"NeutronError": {"type": "ServicePortInUse", "message": "Port 184a0435-4b69-4307-9e53-0eb7073ad9f7 cannot be deleted directly via the port API: has device owner network:ha_router_replicated_interface.", "detail": ""}}
```
and
```bash
Expected HTTP response code [] when accessing …
```
> Make the deletion of network resources more robust

- openstack/compute/v2/servers/utils.go
> Nova v2: search for an exact instance name

- acceptance/gnocchi/metric/v1/resources.go
- acceptance/gnocchi/metric/v1/resourcetypes.go
- gnocchi/metric/v1/resourcetypes/testing/fixtures.go
- gnocchi/metric/v1/resourcetypes/testing/requests_test.go
- openstack/clientconfig/testing/requests_test.go
> Cleanup: fix formatting

- openstack/imageservice/v2/images/utils.go
Remove one unnecessary loop for counting the results when computing
IDFromName.
> imageservice: Refactor: remove one loop

- openstack/clientconfig/requests.go
Previously the openstack.AuthenticatedClient call would create provider and use it to create an authenticated client without the required TLS configuration.
Now the function creates a provider client and updates the HTTPClient before calling Authenticate to setup the client with authentication tokens.
> openstack/clientconfig/requests.go: make sure tls config is generated before creating authenticated client

- terraform/auth/config.go
Hopefully didn't change much and kept all BC. The idea is to allow
the terraform openstack provider to enable logging using the
configuration struct, vs. using environment variables.
Related:
terraform-provider-openstack/terraform-provider-openstack#1246
terraform-provider-openstack/terraform-provider-openstack#1203
> Update: enable logging via config

- openstack/clientconfig/requests.go
- openstack/clientconfig/results.go
Fixes: https://github.com/gophercloud/utils/issues/166
Reopened PR https://github.com/gophercloud/utils/pull/167
> add support for setting a system scope

- openstack/clientconfig/requests.go
> clientconfig.NewServiceClient(): add support for placement and barbican

- terraform/auth/config.go
Required to start work on Mistral resources for [OpenStack Terraform Provider](https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1813)
> feat: add WorkflowV2Client to Terraform utils
